seed: 21

data:
  name: "cifar10"
  root: "./data"
  num_workers: 2

simclr:
  batch_size: 256
  epochs: 100
  lr: 0.4
  momentum: 0.9
  nesterov: false
  min_lr: 0.000001
  weight_decay: 0.0001
  temperature: 0.5
  projection_dim: 128
  embedding_dim: 512
  save_path: "./results/checkpoints/simclr_resnet18.pt"

selection:
  knn_k: 20
  budgets: [10, 20, 50, 100, 200]
  # budgets: [50]
  clustering: "kmeans"
  modified_alpha: 0.7

classifier:
  backbone: "resnet18"
  batch_size: 64
  epochs: 30
  lr: 0.025
  momentum: 0.9
  weight_decay: 0.0005

experiment:
  frameworks: ["fully_supervised", "ssl_embedding", "semi_supervised"]
  # frameworks: ["fully_supervised"]
  methods: ["kcenter", "uncertainty", "margin","entropy", "dbal","bald", "badge","random", "tpcrand", "tpcrp", "tpcinv", "tpcnoclust", "tpcrp_ccfl"]
  # methods: ["random","tpcrand","tpcrp","tpcinv","tpcnoclust", "tpcrp_ccfl"]
  seeds: [42]
  # seeds: [42,43,44]
  iterative_rounds: 2
  initial_labeled: 0
  max_clusters: 500
  min_cluster_size: 5
  mc_passes: 10
  mc_dropout_p: 0.2
