seed: 21

data:
  name: "cifar10"
  root: "./data"
  num_workers: 2

simclr:
  batch_size: 256
  epochs: 500
  lr: 0.4
  momentum: 0.9
  nesterov: false
  min_lr: 0.000001
  weight_decay: 0.0001
  temperature: 0.5
  projection_dim: 128
  embedding_dim: 512
  save_path: "./results/checkpoints/simclr_resnet18.pt"

selection:
  knn_k: 20
  budgets: [10, 20, 30, 50, 100, 150, 200]
  clustering: "kmeans"
  modified_alpha: 0.7

classifier:
  backbone: "resnet18"
  batch_size: 64
  epochs: 50
  lr: 0.025
  momentum: 0.9
  weight_decay: 0.0005

experiment:
  frameworks: ["fully_supervised", "ssl_embedding", "semi_supervised"]
  methods: ["random", "tpcrand", "tpcrp", "tpcinv", "tpcnoclust", "kcenter", "uncertainty", "margin","entropy", "dbal","bald", "badge"]
  # seeds: [42, 43, 44]
  seeds: [42,43,44,45,46,47,48,49,50]
  iterative_rounds: 5
  initial_labeled: 0
  max_clusters: 500
  min_cluster_size: 5
  mc_passes: 10
  mc_dropout_p: 0.2
